package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/go-pdf/fpdf"
)

const (
	pdfMargin       = 12.0
	pdfPageWidth    = 210.0 // A4 portrait, mm
	pdfContentWidth = pdfPageWidth - 2*pdfMargin
	pdfTopRows      = 25
)

// WritePDFReport writes a printable summary alongside the JSON/CSV/YAML outputs.
// titlePrefix (typically the sanitized team name) appears in headers; empty omits it.
func WritePDFReport(path string, r *Report, byMetric []UnusedByMetricRow, plan OTELProcessorPlan, titlePrefix string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(pdfMargin, pdfMargin, pdfMargin)
	pdf.SetAutoPageBreak(true, pdfMargin)

	pdf.SetHeaderFunc(func() {
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(120, 120, 120)
		header := "coralogix-unused-metrics-finder"
		if titlePrefix != "" {
			header += " - " + titlePrefix
		}
		pdf.CellFormat(pdfContentWidth, 6, pdfText(header), "", 1, "R", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
	})
	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(pdfContentWidth, 6, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
	})
	pdf.AddPage()

	writePDFTitle(pdf, titlePrefix)
	writePDFScanSettings(pdf, r)
	writePDFHeadline(pdf, r, byMetric, plan)
	writePDFTopUnused(pdf, byMetric)
	writePDFOTELPlan(pdf, plan)
	writePDFOTELHowTo(pdf)

	return pdf.OutputFileAndClose(path)
}

func writePDFTitle(pdf *fpdf.Fpdf, titlePrefix string) {
	pdf.SetFont("Helvetica", "B", 18)
	title := "Coralogix Unused Metrics Report"
	if titlePrefix != "" {
		title = titlePrefix + " - " + title
	}
	pdf.MultiCell(pdfContentWidth, 9, pdfText(title), "", "L", false)

	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 110)
	pdf.MultiCell(pdfContentWidth, 5, pdfText(
		"Generated by coralogix-unused-metrics-finder. Findings reflect the time window in 'Scan settings' below; "+
			"re-run before acting on production. Stripping labels changes metric identity - validate in staging first."),
		"", "L", false)
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(3)
}

func writePDFScanSettings(pdf *fpdf.Fpdf, r *Report) {
	pdfHeading(pdf, "Scan settings")

	rows := [][2]string{
		{"API host", r.Meta.APIHost},
		{"Dashboards scanned", fmt.Sprintf("%d", r.Meta.DashboardsScanned)},
		{"Alerts scanned", fmt.Sprintf("%d", r.Meta.AlertsScanned)},
		{"SLOs scanned", fmt.Sprintf("%d", r.Meta.SLOsScanned)},
		{"Series lookback", fmt.Sprintf("%d s", r.Meta.SeriesLookbackSeconds)},
		{"Per-metric series limit", fmt.Sprintf("%d", r.Meta.SeriesLimitPerMetric)},
	}
	switch {
	case r.Meta.UsageBillingCalendarMonths > 0:
		rows = append(rows, [2]string{"Billing window", fmt.Sprintf("last %d complete UTC calendar month(s)", r.Meta.UsageBillingCalendarMonths)})
	case r.Meta.UsageLookbackDays > 0:
		rows = append(rows, [2]string{"Billing window", fmt.Sprintf("rolling %d UTC day(s)", r.Meta.UsageLookbackDays)})
	default:
		rows = append(rows, [2]string{"Billing window", "not collected (run with --billing for cost figures)"})
	}
	if r.Meta.UsageBillingUTCStartDate != "" || r.Meta.UsageBillingUTCEndDate != "" {
		rows = append(rows, [2]string{"Billing dates (UTC)", fmt.Sprintf("%s -> %s", r.Meta.UsageBillingUTCStartDate, r.Meta.UsageBillingUTCEndDate)})
	}
	if r.Meta.BillingMetricLookupsAttempted > 0 {
		coverage := fmt.Sprintf("%.0f%% (%d of %d metric lookups succeeded)",
			r.BillingCoverage()*100, r.Meta.BillingMetricLookupsSucceeded, r.Meta.BillingMetricLookupsAttempted)
		switch {
		case r.Meta.BillingPartialAccepted && r.BillingCoverage() < BillingCoverageThreshold:
			coverage += " - partial data accepted via --billing-allow-partial; cost figures understate the total"
		case !r.BillingCoverageSufficient():
			coverage += fmt.Sprintf(" - below the %.0f%% needed to report cost", BillingCoverageThreshold*100)
		}
		rows = append(rows, [2]string{"Billing coverage", coverage})
	}
	if r.Meta.MetricsTruncatedAtSeriesLimit > 0 {
		rows = append(rows, [2]string{"Metrics hit per-metric series cap", fmt.Sprintf("%d (catalog possibly incomplete)", r.Meta.MetricsTruncatedAtSeriesLimit)})
	}
	if r.Meta.SeriesFetchFailuresCount > 0 {
		rows = append(rows, [2]string{"Metrics skipped (series fetch failed)", fmt.Sprintf("%d (usage status unknown)", r.Meta.SeriesFetchFailuresCount)})
		if b := SeriesFetchFailureBreakdown(r.SeriesFetchFailures); b != "" {
			rows = append(rows, [2]string{"  failure categories", b})
		}
	}
	if r.Meta.CoralogixInternalMetricNamesSkipped > 0 {
		rows = append(rows, [2]string{"cx_* metrics skipped", fmt.Sprintf("%d", r.Meta.CoralogixInternalMetricNamesSkipped)})
	}
	writePDFKVTable(pdf, rows)

	if len(r.Warnings) > 0 {
		pdf.Ln(2)
		pdfSubHeading(pdf, "Scan warnings")
		pdf.SetFont("Helvetica", "", 9)
		for _, w := range r.Warnings {
			pdf.MultiCell(pdfContentWidth, 5, pdfText("* "+w), "", "L", false)
		}
	}

	if len(r.SeriesFetchFailures) > 0 {
		pdf.Ln(2)
		pdfSubHeading(pdf, fmt.Sprintf("Metrics excluded from analysis (%d)", len(r.SeriesFetchFailures)))
		pdf.SetFont("Helvetica", "", 9)
		pdf.MultiCell(pdfContentWidth, 5, pdfText(
			"The series catalog for these metric names could not be retrieved - Coralogix refused the query "+
				"(server series-analysis cap), answered with a server error, or it timed out. Typically these "+
				"are the highest-cardinality metrics in the account. They are not in the used/unused "+
				"classification or the OTEL fragment - their usage is unknown, not confirmed unused. Re-run with "+
				"a shorter --series-lookback-hours window, or a larger --timeout-sec for the timed-out ones."),
			"", "L", false)
		limit := pdfTopRows
		if limit > len(r.SeriesFetchFailures) {
			limit = len(r.SeriesFetchFailures)
		}
		pdf.SetFont("Courier", "", 8)
		for _, f := range r.SeriesFetchFailures[:limit] {
			line := "  - " + f.MetricName
			if f.Category != "" {
				line += "  (" + f.Category + ")"
			}
			pdf.MultiCell(pdfContentWidth, 4, pdfText(line), "", "L", false)
		}
		if remaining := len(r.SeriesFetchFailures) - limit; remaining > 0 {
			pdf.SetFont("Helvetica", "I", 8)
			pdf.SetTextColor(110, 110, 110)
			pdf.MultiCell(pdfContentWidth, 4.5, pdfText(
				fmt.Sprintf("  ... %d more - see series_fetch_failures in metric_usage_summary.json.", remaining)),
				"", "L", false)
			pdf.SetTextColor(0, 0, 0)
		}
	}
	pdf.Ln(2)
}

// costCell renders a cost figure, or says why there is none. Without this, a scan with no
// billing data prints "0" for every cost and saving, which reads as a measurement of zero cost
// rather than an absence of data — the worst possible confusion in a customer-facing report.
func costCell(r *Report, formatted string) string {
	if r.BillingCostReportable() {
		return formatted
	}
	if !r.HasBillingData() {
		if r.BillingRequested() {
			return "unavailable - billing lookup returned no data"
		}
		return "not collected - run with --billing"
	}
	return fmt.Sprintf("withheld - billing covered only %.0f%% of metrics (need %.0f%%)",
		r.BillingCoverage()*100, BillingCoverageThreshold*100)
}

func writePDFHeadline(pdf *fpdf.Fpdf, r *Report, byMetric []UnusedByMetricRow, plan OTELProcessorPlan) {
	pdfHeading(pdf, "Headline numbers")

	dropNames := make(map[string]struct{}, len(plan.DropMetricNames))
	for _, n := range plan.DropMetricNames {
		dropNames[n] = struct{}{}
	}

	var (
		dropSeriesCount int
		dropUnitUsage   float64
		dropBytes       uint64
		totalUnitUsage  float64
		totalBytes      uint64
		totalSamples    uint64
	)
	for _, row := range byMetric {
		totalUnitUsage += row.UnitUsageSum
		totalBytes += row.BytesVolumeSum
		totalSamples += row.SampleCountSum
		if _, drop := dropNames[row.MetricName]; drop {
			dropSeriesCount += row.UnusedSeriesCount
			dropUnitUsage += row.UnitUsageSum
			dropBytes += row.BytesVolumeSum
		}
	}
	stripMetricNames := make(map[string]struct{})
	for _, s := range plan.StripStatements {
		stripMetricNames[s.MetricName] = struct{}{}
	}

	totalCatalog := r.Meta.DistinctSeriesInCatalog
	unusedTotal := len(r.UnusedSeriesInCatalog)
	unusedPct := 0.0
	if totalCatalog > 0 {
		unusedPct = 100.0 * float64(unusedTotal) / float64(totalCatalog)
	}

	rows := [][2]string{
		{"Distinct catalog series", commaInt(int64(totalCatalog))},
		{"Used series", commaInt(int64(len(r.UsedSeriesInCatalog)))},
		{"Unused series", fmt.Sprintf("%s (%.1f%% of catalog)", commaInt(int64(unusedTotal)), unusedPct)},
		{"Unused series with CX billing data", costCell(r, fmt.Sprintf("%s of %s", commaInt(int64(r.Meta.UnusedSeriesWithBilling)), commaInt(int64(r.Meta.SeriesWithBillingData))))},
		{"Attributed unit_usage (unused, in window)", costCell(r, formatFloatHuman(totalUnitUsage))},
		{"Attributed bytes_volume (unused, in window)", costCell(r, formatBytes(totalBytes))},
		{"Attributed sample_count (unused, in window)", costCell(r, commaInt(int64(totalSamples)))},
	}
	writePDFKVTable(pdf, rows)
	pdf.Ln(2)

	pdfSubHeading(pdf, "What the OTEL fragment would change")
	rows = [][2]string{
		{"Metrics dropped wholesale", fmt.Sprintf("%d metric name(s), %s series", len(plan.DropMetricNames), commaInt(int64(dropSeriesCount)))},
		{"Estimated unit_usage avoided by drops", costCell(r, formatFloatHuman(dropUnitUsage))},
		{"Estimated bytes_volume avoided by drops", costCell(r, formatBytes(dropBytes))},
		{"Metrics with label keys stripped", fmt.Sprintf("%d metric(s), %d delete_key statement(s)", len(stripMetricNames), len(plan.StripStatements))},
	}
	writePDFKVTable(pdf, rows)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(110, 110, 110)
	pdf.MultiCell(pdfContentWidth, 4.5, pdfText(
		"Drop savings are the sum of attributed unit_usage and bytes_volume on series for fully-unused metric names "+
			"over the billing window above. Label-strip savings depend on cardinality after the strip and aren't "+
			"summed here - inspect per-metric figures in metric_usage_unused_by_metric.csv."),
		"", "L", false)
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(2)
}

func writePDFTopUnused(pdf *fpdf.Fpdf, byMetric []UnusedByMetricRow) {
	if len(byMetric) == 0 {
		return
	}
	pdfHeading(pdf, fmt.Sprintf("Top unused metrics by attributed unit_usage (max %d)", pdfTopRows))

	limit := pdfTopRows
	if limit > len(byMetric) {
		limit = len(byMetric)
	}

	headers := []string{"metric_name", "unit_usage_sum", "unused_series", "with_billing", "bytes_volume_sum"}
	widths := []float64{90, 28, 22, 22, 24}
	aligns := []string{"L", "R", "R", "R", "R"}

	writePDFTableHeader(pdf, headers, widths)
	pdf.SetFont("Helvetica", "", 8)
	for _, row := range byMetric[:limit] {
		cells := []string{
			truncate(row.MetricName, 60),
			formatFloatHuman(row.UnitUsageSum),
			commaInt(int64(row.UnusedSeriesCount)),
			commaInt(int64(row.UnusedSeriesWithBillingCount)),
			formatBytes(row.BytesVolumeSum),
		}
		writePDFTableRow(pdf, cells, widths, aligns)
	}
	if len(byMetric) > limit {
		pdf.Ln(1)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(110, 110, 110)
		pdf.MultiCell(pdfContentWidth, 4.5, pdfText(
			fmt.Sprintf("Showing %d of %d unused metric names - see metric_usage_unused_by_metric.csv for the full list.",
				limit, len(byMetric))),
			"", "L", false)
		pdf.SetTextColor(0, 0, 0)
	}
	pdf.Ln(2)
}

func writePDFOTELPlan(pdf *fpdf.Fpdf, plan OTELProcessorPlan) {
	pdf.AddPage()
	pdfHeading(pdf, "OTEL processor plan")

	if len(plan.DropMetricNames) == 0 && len(plan.StripStatements) == 0 {
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(pdfContentWidth, 5, pdfText(
			"No metrics qualify for dropping or label-stripping under the current scan settings. "+
				"The generated YAML contains 'processors: {}' and adds nothing to your Collector config."),
			"", "L", false)
		return
	}

	if len(plan.DropMetricNames) > 0 {
		pdfSubHeading(pdf, fmt.Sprintf("metrics_usage_drop_unused_metrics - %d metric name(s)", len(plan.DropMetricNames)))
		pdf.SetFont("Helvetica", "", 9)
		pdf.MultiCell(pdfContentWidth, 5, pdfText(
			"Every catalog series for these metric names was unused in the scanned dashboards, alerts, and SLOs. "+
				"The filter processor drops them at the Collector before they reach Coralogix."),
			"", "L", false)
		showDrops := plan.DropMetricNames
		if len(showDrops) > pdfTopRows {
			showDrops = showDrops[:pdfTopRows]
		}
		pdf.SetFont("Courier", "", 8)
		for _, n := range showDrops {
			pdf.MultiCell(pdfContentWidth, 4, pdfText("  - "+n), "", "L", false)
		}
		if remaining := len(plan.DropMetricNames) - len(showDrops); remaining > 0 {
			pdf.SetFont("Helvetica", "I", 8)
			pdf.SetTextColor(110, 110, 110)
			pdf.MultiCell(pdfContentWidth, 4.5, pdfText(
				fmt.Sprintf("  ... %d more - see metric_usage_otel_processors.yaml for the full list.", remaining)),
				"", "L", false)
			pdf.SetTextColor(0, 0, 0)
		}
		pdf.Ln(2)
	}

	if len(plan.StripStatements) > 0 {
		stripsByMetric := make(map[string][]string)
		var metricOrder []string
		for _, s := range plan.StripStatements {
			if _, ok := stripsByMetric[s.MetricName]; !ok {
				metricOrder = append(metricOrder, s.MetricName)
			}
			stripsByMetric[s.MetricName] = append(stripsByMetric[s.MetricName], s.LabelKey)
		}
		sort.Strings(metricOrder)

		pdfSubHeading(pdf, fmt.Sprintf("metrics_usage_strip_unused_only_labels - %d metric(s), %d statement(s)",
			len(metricOrder), len(plan.StripStatements)))
		pdf.SetFont("Helvetica", "", 9)
		pdf.MultiCell(pdfContentWidth, 5, pdfText(
			"For metric names that still have some used series, these label keys appear only on unused series. "+
				"The transform processor deletes them at the Collector. The metric continues to be ingested with "+
				"reduced label cardinality - which changes its identity, so confirm queries still match in staging."),
			"", "L", false)

		limit := pdfTopRows
		if limit > len(metricOrder) {
			limit = len(metricOrder)
		}
		pdf.SetFont("Courier", "", 8)
		for _, mn := range metricOrder[:limit] {
			keys := stripsByMetric[mn]
			sort.Strings(keys)
			pdf.MultiCell(pdfContentWidth, 4,
				pdfText(fmt.Sprintf("  %s -> strip [%s]", mn, strings.Join(keys, ", "))),
				"", "L", false)
		}
		if remaining := len(metricOrder) - limit; remaining > 0 {
			pdf.SetFont("Helvetica", "I", 8)
			pdf.SetTextColor(110, 110, 110)
			pdf.MultiCell(pdfContentWidth, 4.5, pdfText(
				fmt.Sprintf("  ... %d more metric(s) - see metric_usage_otel_processors.yaml for the full list.", remaining)),
				"", "L", false)
			pdf.SetTextColor(0, 0, 0)
		}
	}
	pdf.Ln(2)
}

func writePDFOTELHowTo(pdf *fpdf.Fpdf) {
	pdfHeading(pdf, "How to use metric_usage_otel_processors.yaml")

	steps := []string{
		"Use the otelcol-contrib distribution of the OpenTelemetry Collector. The filter and " +
			"transform processors are not in the upstream core build.",
		"Open metric_usage_otel_processors.yaml from this output bundle and merge its 'processors:' block " +
			"into your existing Collector config. Two processor IDs are defined: " +
			"metrics_usage_drop_unused_metrics and metrics_usage_strip_unused_only_labels.",
		"Reference both processors in your metrics pipeline. Recommended order: drop first, then strip, " +
			"so the transform processor never sees datapoints destined for the bin.",
	}
	pdf.SetFont("Helvetica", "", 10)
	for i, s := range steps {
		pdf.MultiCell(pdfContentWidth, 5, pdfText(fmt.Sprintf("%d. %s", i+1, s)), "", "L", false)
		pdf.Ln(1)
	}

	pdf.SetFont("Courier", "", 8)
	pdf.MultiCell(pdfContentWidth, 4, pdfText(
		"service:\n"+
			"  pipelines:\n"+
			"    metrics:\n"+
			"      receivers: [prometheus, ...]\n"+
			"      processors:\n"+
			"        - memory_limiter\n"+
			"        - metrics_usage_drop_unused_metrics\n"+
			"        - metrics_usage_strip_unused_only_labels\n"+
			"        - batch\n"+
			"      exporters: [...]"),
		"", "L", false)
	pdf.Ln(2)

	more := []string{
		"The label-strip statements are written for the prometheusreceiver layout, where scrape labels live " +
			"on datapoint attributes. If your pipeline uses a different placement (resource attributes, OTLP-native " +
			"sources, etc.) adjust the OTTL context or rewrite the statements.",
		"Roll out in staging first. Stripping a label changes a metric's identity - dashboards or alerts that " +
			"group by the dropped label will start aggregating across previously-distinct series. Keep the previous " +
			"Collector config available for rollback.",
		"Re-run coralogix-unused-metrics-finder periodically. A series that's unused this week may become used " +
			"when a new dashboard or alert is created - the generated YAML is a point-in-time snapshot.",
	}
	pdf.SetFont("Helvetica", "", 10)
	for i, s := range more {
		pdf.MultiCell(pdfContentWidth, 5, pdfText(fmt.Sprintf("%d. %s", i+4, s)), "", "L", false)
		pdf.Ln(1)
	}

	pdfSubHeading(pdf, "Caveats")
	caveats := []string{
		"If you ran with --skip-dashboards, --skip-alerts, or --skip-slo, the OTEL plan only excludes references " +
			"from the sources that were scanned. Skipping all three makes every catalog series appear unused.",
		"If any metric hit --series-limit-per-metric (see Scan settings), the catalog may be incomplete; some " +
			"series under that metric name were never compared, so the drop entry could be too aggressive. Increase " +
			"the limit and re-run before applying.",
		"Coralogix internal metrics (prefix cx_) are excluded from the scan entirely and never appear in drops or strips.",
	}
	pdf.SetFont("Helvetica", "", 9)
	for _, c := range caveats {
		pdf.MultiCell(pdfContentWidth, 5, pdfText("* "+c), "", "L", false)
	}
}

func pdfHeading(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "B", 13)
	pdf.MultiCell(pdfContentWidth, 7, pdfText(text), "", "L", false)
	pdf.Ln(1)
}

func pdfSubHeading(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.MultiCell(pdfContentWidth, 5.5, pdfText(text), "", "L", false)
	pdf.Ln(0.5)
}

func writePDFKVTable(pdf *fpdf.Fpdf, rows [][2]string) {
	pdf.SetFont("Helvetica", "", 9)
	labelW := 75.0
	valueW := pdfContentWidth - labelW
	for _, row := range rows {
		pdf.CellFormat(labelW, 5.5, pdfText(row[0]), "", 0, "L", false, 0, "")
		pdf.CellFormat(valueW, 5.5, pdfText(row[1]), "", 1, "L", false, 0, "")
	}
}

func writePDFTableHeader(pdf *fpdf.Fpdf, headers []string, widths []float64) {
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(225, 225, 225)
	for i, h := range headers {
		align := "L"
		if i > 0 {
			align = "R"
		}
		pdf.CellFormat(widths[i], 5, pdfText(h), "B", 0, align, true, 0, "")
	}
	pdf.Ln(-1)
}

func writePDFTableRow(pdf *fpdf.Fpdf, cells []string, widths []float64, aligns []string) {
	for i, c := range cells {
		align := "L"
		if i < len(aligns) {
			align = aligns[i]
		}
		pdf.CellFormat(widths[i], 4.5, pdfText(c), "", 0, align, false, 0, "")
	}
	pdf.Ln(-1)
}

func formatFloatHuman(v float64) string {
	switch {
	case v == 0:
		return "0"
	case v < 1:
		return fmt.Sprintf("%.4f", v)
	case v < 1000:
		return fmt.Sprintf("%.2f", v)
	default:
		return commaInt(int64(v))
	}
}

func formatBytes(v uint64) string {
	if v == 0 {
		return "0 B"
	}
	const unit = 1024
	if v < unit {
		return fmt.Sprintf("%d B", v)
	}
	div, exp := uint64(unit), 0
	for n := v / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	suffix := []string{"KiB", "MiB", "GiB", "TiB", "PiB"}[exp]
	return fmt.Sprintf("%.2f %s", float64(v)/float64(div), suffix)
}

func commaInt(v int64) string {
	neg := v < 0
	if neg {
		v = -v
	}
	s := fmt.Sprintf("%d", v)
	n := len(s)
	if n <= 3 {
		if neg {
			return "-" + s
		}
		return s
	}
	var out strings.Builder
	if neg {
		out.WriteByte('-')
	}
	first := n % 3
	if first > 0 {
		out.WriteString(s[:first])
		if n > first {
			out.WriteByte(',')
		}
	}
	for i := first; i < n; i += 3 {
		out.WriteString(s[i : i+3])
		if i+3 < n {
			out.WriteByte(',')
		}
	}
	return out.String()
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	if max <= 3 {
		return s[:max]
	}
	return s[:max-1] + "~"
}

// pdfText sanitizes for the Latin-1 (Windows-1252) core fonts that fpdf ships
// without a TTF — multi-byte runes are replaced with ASCII equivalents or "?".
func pdfText(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch {
		case r == '…':
			b.WriteString("...")
		case r == '→':
			b.WriteString("->")
		case r == '—':
			b.WriteString(" - ")
		case r == '–':
			b.WriteByte('-')
		case r == '•':
			b.WriteByte('*')
		case r == '·':
			b.WriteByte('.')
		case r == ' ':
			b.WriteByte(' ')
		case r == '\n' || r == '\t':
			b.WriteRune(r)
		case r >= 0x20 && r < 0x100:
			b.WriteRune(r)
		default:
			b.WriteByte('?')
		}
	}
	return b.String()
}
